project_to_scan_path = "/Users/palazzoc0905/Studio/oao-webplex/"
analysis_only = true
ignore_dirs = [
    ".githooks",
    ".github",
    ".storybook",
    ".storybookWPX",
    ".storyShots",
    ".vscode",
    "jenkins",
    "scripts",
    "tools",
    "vars",
    "coverage",
    "node_modules",
    "storybook-static",
    "dist"
]
dependencies_whitelist = [
    "^@viacom/",
    "^@storybook/",
    "^@testing-library/",
    "^@types/",
    "^@paramount/",
    "^@data-model/",
    ".*typescript.*",
    "tslib",
    "zim",
    "^@nrwl/",
    ".*babel.*",
    "^@loadable/",
    "^postcss",
    ".*react.*",
    "^eslint",
    ".*jest.*",
    ".*enzyme-to-json.*"
]
